CREATE TABLE IF NOT EXISTS b_booking_client_type (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	MODULE_ID varchar(255) NOT NULL,
	CODE varchar(255) NOT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_booking_client_type_module_id_code ON b_booking_client_type (module_id, code);

CREATE TABLE IF NOT EXISTS b_booking_resource_type (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	MODULE_ID varchar(255) NOT NULL,
	CODE varchar(255) DEFAULT NULL,
	NAME varchar(255) DEFAULT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_booking_resource_type_module_id_code ON b_booking_resource_type (module_id, code);

CREATE TABLE IF NOT EXISTS b_booking_resource_type_notification_settings (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	TYPE_ID int8 NOT NULL,
	IS_INFO_ON char(1) NOT NULL DEFAULT 'Y',
	TEMPLATE_TYPE_INFO varchar(255) NOT NULL,
	INFO_DELAY int8 NOT NULL DEFAULT 0,
	IS_CANCELLATION_ON char(1) NOT NULL DEFAULT 'Y',
	CANCELLATION_DELAY int NOT NULL DEFAULT 600,
	IS_CONFIRMATION_ON char(1) NOT NULL DEFAULT 'Y',
	TEMPLATE_TYPE_CONFIRMATION varchar(255) NOT NULL,
	CONFIRMATION_DELAY int8 NOT NULL DEFAULT 86400,
	CONFIRMATION_REPETITIONS int8 NOT NULL DEFAULT 0,
	CONFIRMATION_REPETITIONS_INTERVAL int8 NOT NULL DEFAULT 10800,
	CONFIRMATION_COUNTER_DELAY int8 NOT NULL DEFAULT 10800,
	IS_REMINDER_ON char(1) NOT NULL DEFAULT 'Y',
	TEMPLATE_TYPE_REMINDER varchar(255) NOT NULL,
	REMINDER_DELAY int8 NOT NULL DEFAULT -1,
	IS_FEEDBACK_ON char(1) NOT NULL DEFAULT 'Y',
	TEMPLATE_TYPE_FEEDBACK varchar(255) NOT NULL,
	IS_DELAYED_ON char(1) NOT NULL DEFAULT 'Y',
	TEMPLATE_TYPE_DELAYED varchar(255) NOT NULL,
	DELAYED_DELAY int8 NOT NULL DEFAULT 300,
	DELAYED_COUNTER_DELAY int8 NOT NULL DEFAULT 300,
	SENDER_CODE varchar(255) NOT NULL DEFAULT 'bitrix24',
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_booking_resource (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	TYPE_ID int8 NOT NULL,
	EXTERNAL_ID int8 DEFAULT NULL,
	IS_MAIN char(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_booking_resource_type_id ON b_booking_resource (type_id);
CREATE INDEX ix_b_booking_resource_external_id ON b_booking_resource (external_id);
CREATE INDEX ix_b_booking_resource_is_main ON b_booking_resource (is_main);

CREATE TABLE IF NOT EXISTS b_booking_resource_data (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	RESOURCE_ID int8 NOT NULL,
	AVATAR_ID int DEFAULT NULL,
	NAME varchar(255) NOT NULL,
	DESCRIPTION text,
	IS_DELETED char(1) NOT NULL DEFAULT 'N',
	DELETED_AT timestamp NULL DEFAULT NULL,
	CREATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY int8 NOT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_booking_resource_data_resource_id ON b_booking_resource_data (resource_id);
CREATE INDEX ix_b_booking_resource_data_is_deleted ON b_booking_resource_data (is_deleted);

CREATE TABLE IF NOT EXISTS b_booking_resource_settings (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	RESOURCE_ID int8 NOT NULL,
	WEEKDAYS varchar(50) NOT NULL,
	SLOT_SIZE int8 DEFAULT NULL,
	TIME_FROM int8 NOT NULL,
	TIME_TO int8 NOT NULL,
	TIMEZONE varchar(50) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_booking_resource_notification_settings (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	RESOURCE_ID int8 NOT NULL,
	IS_INFO_ON char(1) NOT NULL DEFAULT 'Y',
	TEMPLATE_TYPE_INFO varchar(255) NOT NULL,
	INFO_DELAY int8 NOT NULL DEFAULT 0,
	IS_CANCELLATION_ON char(1) NOT NULL DEFAULT 'Y',
	CANCELLATION_DELAY int NOT NULL DEFAULT 600,
	IS_CONFIRMATION_ON char(1) NOT NULL DEFAULT 'Y',
	TEMPLATE_TYPE_CONFIRMATION varchar(255) NOT NULL,
	CONFIRMATION_DELAY int8 NOT NULL DEFAULT 86400,
	CONFIRMATION_REPETITIONS int8 NOT NULL DEFAULT 0,
	CONFIRMATION_REPETITIONS_INTERVAL int8 NOT NULL DEFAULT 10800,
	CONFIRMATION_COUNTER_DELAY int8 NOT NULL DEFAULT 10800,
	IS_REMINDER_ON char(1) NOT NULL DEFAULT 'Y',
	TEMPLATE_TYPE_REMINDER varchar(255) NOT NULL,
	REMINDER_DELAY int8 NOT NULL DEFAULT -1,
	IS_FEEDBACK_ON char(1) NOT NULL DEFAULT 'Y',
	TEMPLATE_TYPE_FEEDBACK varchar(255) NOT NULL,
	IS_DELAYED_ON char(1) NOT NULL DEFAULT 'Y',
	TEMPLATE_TYPE_DELAYED varchar(255) NOT NULL,
	DELAYED_DELAY int8 NOT NULL DEFAULT 300,
	DELAYED_COUNTER_DELAY int8 NOT NULL DEFAULT 300,
	SENDER_CODE varchar(255) NOT NULL DEFAULT 'bitrix24',
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ix_brns_resource_id ON b_booking_resource_notification_settings (resource_id);

CREATE TABLE IF NOT EXISTS b_booking_booking (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	NAME varchar(255) DEFAULT NULL,
	DATE_FROM int8 NOT NULL,
	DATE_TO int8 NOT NULL,
	TIMEZONE_FROM varchar(50) NOT NULL,
	TIMEZONE_FROM_OFFSET int NOT NULL,
	TIMEZONE_TO varchar(50) NOT NULL,
	TIMEZONE_TO_OFFSET int NOT NULL,
	DATE_MAX int8 NOT NULL,
	IS_RECURRING char(1) NOT NULL DEFAULT 'N',
	RRULE text,
	PARENT_ID int8 DEFAULT NULL,
	IS_DELETED char(1) NOT NULL DEFAULT 'N',
	IS_CONFIRMED char(1) NOT NULL DEFAULT 'N',
	DESCRIPTION text,
	VISIT_STATUS varchar(20) NOT NULL DEFAULT 'unknown',
	SOURCE varchar(20) NOT NULL DEFAULT 'internal',
	DELETION_SCENARIO varchar(20) DEFAULT NULL,
	CREATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
	DELETED_AT timestamp NULL DEFAULT NULL,
	CREATED_BY int8 NOT NULL,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_booking_booking_date_from_date_to ON b_booking_booking (date_from, date_to);
CREATE INDEX ix_b_booking_booking_date_max ON b_booking_booking (date_max);
CREATE INDEX ix_b_booking_booking_parent_id ON b_booking_booking (parent_id);
CREATE INDEX ix_b_booking_booking_created_at ON b_booking_booking (created_at);
CREATE INDEX ix_b_booking_booking_created_by ON b_booking_booking (created_by);
CREATE INDEX ix_b_booking_booking_is_deleted_date_from_date_max ON b_booking_booking (is_deleted, date_from, date_max)
CREATE INDEX ix_b_booking_booking_is_deleted_date_max_date_from ON b_booking_booking (is_deleted, date_max, date_from)

CREATE TABLE IF NOT EXISTS b_booking_booking_resource (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	BOOKING_ID int8 NOT NULL,
	RESOURCE_ID int8 NOT NULL,
	IS_PRIMARY char(1) NOT NULL DEFAULT 'N',
	IS_DELETED char(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_booking_booking_resource_booking_id_resource_id ON b_booking_booking_resource (booking_id, resource_id);
CREATE INDEX ix_b_booking_booking_resource_booking_id_is_primary ON b_booking_booking_resource (booking_id, is_primary);

CREATE TABLE IF NOT EXISTS b_booking_booking_client (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	BOOKING_ID int8 DEFAULT NULL,
	ENTITY_ID int8 NOT NULL,
	CLIENT_TYPE_ID int8 NOT NULL,
	CLIENT_ID int8 NOT NULL,
	IS_PRIMARY char(1) NOT NULL DEFAULT 'N',
	ENTITY_TYPE varchar(255) NOT NULL DEFAULT 'booking',
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ix_b_booking_booking_client_entity_id_client_type_id_client_id ON b_booking_booking_client (entity_id, entity_type, client_type_id, client_id);
CREATE INDEX ix_b_booking_booking_client_client_type_id_client_id ON b_booking_booking_client (client_type_id, client_id);

CREATE TABLE IF NOT EXISTS b_booking_booking_external_data (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	BOOKING_ID int8 DEFAULT NULL,
	ENTITY_ID int8 NOT NULL,
	MODULE_ID varchar(255) NOT NULL,
	ENTITY_TYPE_ID varchar(255) NOT NULL,
	VALUE varchar(255) NOT NULL,
	ENTITY_TYPE varchar(255) NOT NULL DEFAULT 'booking',
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_booking_booking_external_data_entity_id_entity_type ON b_booking_booking_external_data (entity_id, entity_type);
CREATE INDEX ix_b_booking_booking_external_data_module_id_entity_type_id_val ON b_booking_booking_external_data (module_id, entity_type_id, value);

CREATE TABLE IF NOT EXISTS b_booking_journal (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	ENTITY_ID int8 NOT NULL,
	TYPE varchar(64) NOT NULL,
	DATA text NOT NULL,
	STATUS varchar(10) NOT NULL,
	INFO varchar(512) DEFAULT NULL,
	CREATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_booking_journal_entity_id ON b_booking_journal (entity_id);
CREATE INDEX ix_b_booking_journal_type ON b_booking_journal (type);
CREATE INDEX ix_b_booking_journal_status ON b_booking_journal (status);
CREATE INDEX ix_b_booking_journal_created_at ON b_booking_journal (created_at);

CREATE TABLE IF NOT EXISTS b_booking_favorites (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	MANAGER_ID int8 NOT NULL,
	RESOURCE_ID int8 NOT NULL,
	TYPE varchar(10) NOT NULL DEFAULT 'ADDED',
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_booking_favorites_resource_id ON b_booking_favorites (resource_id);
CREATE UNIQUE INDEX ux_b_booking_favorites_manager_id_resource_id ON b_booking_favorites (manager_id, resource_id);

CREATE TABLE IF NOT EXISTS b_booking_scorer (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	USER_ID int NOT NULL DEFAULT 0,
	ENTITY_ID int NOT NULL DEFAULT 0,
	TYPE varchar(64) NOT NULL DEFAULT '',
	VALUE int8 NOT NULL DEFAULT 0,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_booking_scorer_user_id_entity_id_type ON b_booking_scorer (user_id, entity_id, type);
CREATE INDEX ix_b_booking_scorer_user_id ON b_booking_scorer (user_id);
CREATE INDEX ix_b_booking_scorer_type ON b_booking_scorer (type);
CREATE INDEX ix_b_booking_scorer_entity_id ON b_booking_scorer (entity_id);

CREATE TABLE IF NOT EXISTS b_booking_booking_note (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	BOOKING_ID int8 DEFAULT NULL,
	ENTITY_ID int8 NOT NULL,
	DESCRIPTION text NOT NULL,
	ENTITY_TYPE varchar(255) NOT NULL DEFAULT 'booking',
	NOTE_TYPE varchar(255) NOT NULL DEFAULT 'manager',
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ix_bbn_entity_id_entity_type_note_type ON b_booking_booking_note (entity_id, entity_type, note_type);

CREATE TABLE IF NOT EXISTS b_booking_option (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	USER_ID int NOT NULL,
	NAME varchar(255) NOT NULL,
	VALUE varchar(255) NOT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_booking_option_user_id_name ON b_booking_option (user_id, name);

CREATE TABLE IF NOT EXISTS b_booking_booking_message (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	BOOKING_ID int8 NOT NULL,
	NOTIFICATION_TYPE varchar(255) NOT NULL,
	SENDER_MODULE_ID varchar(255) DEFAULT NULL,
	SENDER_CODE varchar(255) NOT NULL,
	EXTERNAL_MESSAGE_ID varchar(255) NOT NULL,
	CREATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_booking_booking_message_booking_id_notification_type_sende ON b_booking_booking_message (booking_id, notification_type, sender_code, created_at);
CREATE INDEX ix_b_booking_booking_message_sender_code_external ON b_booking_booking_message (sender_code, external_message_id);

CREATE TABLE IF NOT EXISTS b_booking_booking_message_failure_log (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	BOOKING_ID int8 NOT NULL,
	NOTIFICATION_TYPE varchar(255) NOT NULL,
	SENDER_MODULE_ID varchar(255) NOT NULL,
	SENDER_CODE varchar(255) NOT NULL,
	REASON_CODE varchar(255) NOT NULL,
	REASON_TEXT text,
	CREATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_booking_booking_message_failure_log_booking_id_notificatio ON b_booking_booking_message_failure_log (booking_id, notification_type, sender_module_id, sender_code, created_at);
CREATE INDEX ix_bbmfl_complex_2 ON b_booking_booking_message_failure_log (booking_id, notification_type, created_at);

CREATE TABLE IF NOT EXISTS b_booking_wait_list_item (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	CREATED_BY int8 NOT NULL,
	CREATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
	IS_DELETED char(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_booking_wait_list_item_is_deleted ON b_booking_wait_list_item (is_deleted);

CREATE TABLE IF NOT EXISTS b_booking_resource_linked_entity (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	RESOURCE_ID int8 NOT NULL,
	ENTITY_ID int8 NOT NULL,
	ENTITY_TYPE varchar(255) NOT NULL,
	CREATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
	DATA text DEFAULT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ix_b_booking_resource_entity_resource_linked_entity ON b_booking_resource_linked_entity (resource_id, entity_id, entity_type);

CREATE TABLE IF NOT EXISTS b_booking_delayed_task (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	CODE varchar(32) NOT NULL,
	TYPE varchar(64) NOT NULL,
	DATA text NOT NULL,
	STATUS varchar(10) NOT NULL,
	CREATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_booking_delayed_task_status ON b_booking_delayed_task (status);

CREATE TABLE IF NOT EXISTS b_booking_booking_sku (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	BOOKING_ID int NOT NULL,
	SKU_ID int NOT NULL,
	PRODUCT_ROW_ID int DEFAULT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_booking_booking_sku_booking_id_sku ON b_booking_booking_sku (booking_id, sku_id);
CREATE UNIQUE INDEX ux_b_booking_booking_sku_product_row ON b_booking_booking_sku (product_row_id);
CREATE INDEX ix_b_booking_booking_sku_sku ON b_booking_booking_sku (sku_id);

CREATE TABLE IF NOT EXISTS b_booking_resource_sku (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	RESOURCE_ID int NOT NULL,
	SKU_ID int NOT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_booking_resource_sku_resource_id_sku ON b_booking_resource_sku (resource_id, sku_id);
CREATE INDEX ix_b_booking_resource_sku_sku ON b_booking_resource_sku (sku_id);

CREATE TABLE IF NOT EXISTS b_booking_resource_sku_yandex (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	RESOURCE_ID int NOT NULL,
	SKU_ID int NOT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_booking_resource_sku_yandex ON b_booking_resource_sku_yandex (resource_id, sku_id);
CREATE INDEX ix_b_booking_resource_sku_yandex_sku ON b_booking_resource_sku_yandex (sku_id);

CREATE TABLE IF NOT EXISTS b_booking_booking_payment (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	BOOKING_ID int NOT NULL,
	PAYMENT_ID int NOT NULL,
	IS_PAID char(1) NOT NULL DEFAULT 'N',
	IS_PAID_MANUALLY char(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ix_bbp_payment_id ON b_booking_booking_payment (payment_id);
