<?php

return [
	'extensions' => [
		'type',
		'tokens',
		'assets/icons',
		'layout/ui/menu',
		'require-lazy',
		'device/connection',
		'animation/animated',
		'ui-system/typography',
		'ui-system/layout/area',
		'ui-system/blocks/icon',
		'utils/object',

		'im:messenger/const',
		'im:messenger/provider/services/chat',
		'im:messenger/provider/services/recent',
		'im:messenger/provider/services/analytics',
		'im:messenger/lib/di/service-locator',
		'im:messenger/lib/utils',
		'im:messenger/lib/logger',
		'im:messenger/lib/permission-manager',
		'im:messenger/lib/rest-manager',
		'im:messenger/lib/element/chat-title',
		'im:messenger/lib/helper',
		'im:messenger/lib/params',
		'im:messenger/lib/ui/notification',
		'im:messenger/controller/sidebar-v2/const',
		'im:messenger/controller/sidebar-v2/ui/primary-button',
		'im:messenger/controller/sidebar-v2/search',
		'im:messenger/controller/sidebar-v2/loc',
		'im:messenger/controller/dialog/lib/helper/text',
		'im:messenger/controller/sidebar-v2/ui/layout/work-position',
		'im:messenger/controller/sidebar-v2/ui/chat-description',
		'im:messenger/controller/sidebar-v2/ui/sidebar-avatar',
		'im:messenger/controller/sidebar-v2/ui/top-container',
		'im:messenger/controller/sidebar-v2/ui/plan-limit-banner',
		'im:messenger/lib/params',
		'im:messenger/lib/message-auto-delete',
		'im:messenger/controller/sidebar-v2/factory',
		'ui-system/layout/card-list',
		'im:messenger/lib/messages-auto-delete',
	],
	'bundle' => [
		'./src/view',
		'./src/permission-manager',
		'./src/widget-navigator',
	],
];
