<?php

return [
	'components' => [
		'intranet:qualification',
	],
	'extensions' => [
		'analytics',
		'apptheme',
		'background/ui-manager',
		'layout/pure-component',
		'layout/ui/menu',
		'layout/ui/smartphone-contact-selector',
		'layout/ui/status-box',
		'layout/ui/wizard',
		'layout/ui/wizard/const',
		'layout/ui/wizard/step',
		'layout/ui/wizard/step-layout',
		'loc',
		'notify-manager',
		'rest/run-action-executor',
		'toast',
		'tokens',
		'type',
		'ui-system/blocks/icon',
		'ui-system/blocks/link',
		'ui-system/form/buttons',
		'ui-system/form/inputs/multi-email',
		'ui-system/form/inputs/phone',
		'ui-system/layout/box',
		'ui-system/layout/dialog-footer',
		'ui-system/typography',
		'utils/function',
		'utils/object',
		'utils/phone',
		'utils/test',
		'utils/validation',
		'intranet:invite-new',
		'intranet:invite-opener-new/api',
	],
	'bundle' => [
		'./src/analytics-handler',
		'./src/api',
		'./src/const',
		'./src/fields/balloon-select',
		'./src/fields/phone',
		'./src/fields/user-invitation',
		'./src/fields-handler',
		'./src/fields-triggers-handler',
		'./src/step',
		'./src/step-layout',
		'./src/utils',
	],
];
