<?php

return [
	'extensions' => [
		'runtime',
		'type',
		'utils/object',
		'im:messenger/const',
		'im:messenger/const/rest',
		'im:messenger/lib/converter/data/recent',
		'im:messenger/lib/counters/update-system/action/read-message/local',
		'im:messenger/lib/di/service-locator',
		'im:messenger/lib/emitter',
		'im:messenger/lib/feature',
		'im:messenger/lib/helper',
		'im:messenger/lib/integration/callmobile/call-manager',
		'im:messenger/lib/logger',
		'im:messenger/lib/params',
		'im:messenger/lib/rest',
		'im:messenger/lib/rest-manager',
		'im:messenger/lib/uuid-manager',
		'im:messenger/provider/data',
		'im:messenger/provider/services/lib/chat-data-extractor',
		'im:messenger/provider/services/lib/message-context-creator',
		'im:messenger/provider/services/message',
	],
	'bundle' => [
		'./src/bot',
		'./src/comments',
		'./src/create',
		'./src/health-check',
		'./src/input-action-notify',
		'./src/load',
		'./src/mute',
		'./src/read',
		'./src/service',
		'./src/update',
		'./src/user',
		'../../../const/src/rest',
	],
];
