<?php

return [
	'extensions' => [
		'type',
		'utils/array',
		'im:messenger/const',
		'im:messenger/db/const',
		'im:messenger/db/helper/fulltext',
		'im:messenger/db/helper/start-words',
		'im:messenger/lib/di/service-locator',
		'im:messenger/lib/feature',
		'im:messenger/lib/helper',
		'im:messenger/lib/logger',
	],
	'bundle' => [
		'./src/comment',
		'./src/copilot',
		'./src/counter',
		'./src/dialog',
		'./src/draft',
		'./src/file',
		'./src/internal/counter-pending-operation',
		'./src/internal/dialog',
		'./src/link-pin',
		'./src/link-pin-message',
		'./src/message',
		'./src/message-push',
		'./src/option',
		'./src/queue',
		'./src/reaction',
		'./src/read-message-queue',
		'./src/recent',
		'./src/sidebar/file',
		'./src/smile',
		'./src/sticker',
		'./src/table',
		'./src/temp-message',
		'./src/transcript',
		'./src/user',
		'./src/vote',
	],
];
