<?php

return [
	'extensions' => [
		'im:messenger/provider/pull/base',
		'type',
		'utils/object',
		'im:messenger/loc',
		'im:messenger/lib/di/service-locator',
		'im:messenger/const',
		'im:messenger/lib/converter/data/recent',
		'im:messenger/lib/element/chat-title',
		'im:messenger/lib/element/chat-avatar',
		'im:messenger/lib/helper',
		'im:messenger/lib/logger',
		'im:messenger/lib/params',
		'im:messenger/lib/parser',
		'im:messenger/lib/notifier',
		'im:messenger/lib/emitter',
		'im:messenger/lib/uuid-manager',
		'im:messenger/lib/feature',
		'im:messenger/cache/share-dialog',
		'im:messenger/provider/service/sync',
		'im:chat/utils',
		'im:chat/messengercommon',
		'im:chat/dataconverter',
		'im:messenger/provider/pull/lib/new-message-manager/chat',
		'im:messenger/provider/pull/lib/recent/chat/update-manager',
		'im:messenger/provider/pull/lib/file',
		'im:messenger/provider/data',
		'im:messenger/lib/feature',
	],
	'bundle' => [
		'./src/file',
		'./src/notification',
		'./src/online',
	],
];
