CREATE TABLE IF NOT EXISTS b_baas_services (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	CODE varchar(128) NOT NULL,
	ICON_CLASS varchar(255),
	ICON_COLOR varchar(255),
	ICON_STYLE varchar(1000),
	TITLE varchar(255),
	ACTIVE_SUBTITLE varchar(255),
	INACTIVE_SUBTITLE varchar(255),
	DESCRIPTION varchar(1000),
	FEATURE_PROMOTION_CODE varchar(255),
	HELPER_CODE varchar(255),
	ADVERTISING_STRATEGY varchar(255),
	CURRENT_VALUE int NOT NULL DEFAULT 0,
	MINIMAL_VALUE int DEFAULT NULL,
	MAXIMAL_VALUE int NOT NULL DEFAULT 0,
	EXPIRATION_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	SORT int NOT NULL DEFAULT 100,
	RENEWABLE char(1) NOT NULL DEFAULT 'N',
	LANGUAGE_INFO text,
	STATE_NUMBER int DEFAULT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_baas_services_code ON b_baas_services (code);
CREATE TABLE IF NOT EXISTS b_baas_service_ads (
	SERVICE_CODE varchar(128) NOT NULL,
	LANGUAGE_ID varchar(2),
	TITLE varchar(255),
	SUBTITLE varchar(255),
	SUBTITLE_DESCRIPTION varchar(255),
	FEATURE_PROMOTION_CODE varchar(255),
	HELPER_CODE varchar(255),
	ICON_URL varchar(1000),
	ICON_FILE_TYPE varchar(255),
	VIDEO_URL varchar(1000),
	VIDEO_FILE_TYPE varchar(255)
);
CREATE UNIQUE INDEX ux_b_baas_service_ads_service_code_language_id ON b_baas_service_ads (service_code, language_id);
CREATE TABLE IF NOT EXISTS b_baas_package (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	CODE varchar(128) NOT NULL,
	ICON_CLASS varchar(255),
	ICON_COLOR varchar(255),
	ICON_STYLE varchar(1000),
	PURCHASE_URL varchar(1000),
	TITLE varchar(255),
	DESCRIPTION varchar(1000),
	FEATURE_PROMOTION_CODE varchar(255),
	HELPER_CODE varchar(255),
	DISTRIBUTION_STRATEGY varchar(255),
	PRICE_VALUE decimal NOT NULL DEFAULT 0,
	PRICE_CURRENCY_ID varchar(3),
	PRICE_DESCRIPTION varchar(1000),
	ACTIVE char(1) NOT NULL DEFAULT 'Y',
	SORT int NOT NULL DEFAULT 100,
	LANGUAGE_INFO text,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_baas_package_code ON b_baas_package (code);
CREATE TABLE IF NOT EXISTS b_baas_service_in_package (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	PACKAGE_CODE varchar(128) NOT NULL,
	SERVICE_CODE varchar(128) NOT NULL,
	VALUE int NOT NULL DEFAULT 0,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_baas_service_in_package_service_code_package_code ON b_baas_service_in_package (service_code, package_code);
CREATE TABLE IF NOT EXISTS b_baas_purchase (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	CODE varchar(128) NOT NULL,
	PURCHASE_URL varchar(1000),
	PURGED char(1) NOT NULL DEFAULT 'N',
	NOTIFIED char(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_baas_purchase_code ON b_baas_purchase (code);
CREATE TABLE IF NOT EXISTS b_baas_purchased_package (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	CODE varchar(128) NOT NULL,
	PACKAGE_CODE varchar(128) NOT NULL,
	PURCHASE_CODE varchar(128) NOT NULL,
	START_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	EXPIRATION_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ACTIVE char(1) NOT NULL DEFAULT 'Y',
	NOTIFIED CHAR(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_baas_purchased_package_code ON b_baas_purchased_package (code);
CREATE INDEX ix_b_baas_purchased_package_code_package_code ON b_baas_purchased_package (code, package_code);
CREATE INDEX ix_b_baas_purchased_package_code_purchase_code ON b_baas_purchased_package (code, purchase_code);
CREATE TABLE IF NOT EXISTS b_baas_service_in_purchased_pack (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	PURCHASED_PACKAGE_CODE varchar(128) NOT NULL,
	SERVICE_CODE varchar(128) NOT NULL,
	CURRENT_VALUE int NOT NULL DEFAULT 0,
	STATE_NUMBER int DEFAULT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_baas_service_in_purchased_pack_purchased_package_code_serv ON b_baas_service_in_purchased_pack (purchased_package_code, service_code);
CREATE INDEX ix_b_baas_service_in_purchased_pack_service_code_curv ON b_baas_service_in_purchased_pack (service_code, current_value);
