create table if not exists b_baas_services
(
	ID INT NOT NULL AUTO_INCREMENT,
	`CODE` VARCHAR(128) NOT NULL,

	ICON_CLASS VARCHAR(255),
	ICON_COLOR VARCHAR(255),
	ICON_STYLE VARCHAR(1000),
	TITLE VARCHAR(255),
	ACTIVE_SUBTITLE VARCHAR(255),
	INACTIVE_SUBTITLE VARCHAR(255),
	DESCRIPTION VARCHAR(1000),
	FEATURE_PROMOTION_CODE VARCHAR(255),
	HELPER_CODE VARCHAR(255),
	ADVERTISING_STRATEGY VARCHAR(255),

	CURRENT_VALUE INT NOT NULL DEFAULT 0,
	MINIMAL_VALUE INT DEFAULT NULL,
	MAXIMAL_VALUE INT NOT NULL DEFAULT 0,

    EXPIRATION_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	SORT INT NOT NULL DEFAULT 100,
	RENEWABLE CHAR(1) NOT NULL DEFAULT 'N',

	LANGUAGE_INFO text,

	STATE_NUMBER BIGINT UNSIGNED NULL,

	primary key (ID),
	unique index `ux_baas_services_code` (`CODE`)
);

create table if not exists b_baas_service_ads
(
	SERVICE_CODE VARCHAR(128) NOT NULL,
	LANGUAGE_ID VARCHAR(2),

	TITLE VARCHAR(255),
	SUBTITLE VARCHAR(255),
	SUBTITLE_DESCRIPTION VARCHAR(255),
	FEATURE_PROMOTION_CODE VARCHAR(255),
	HELPER_CODE VARCHAR(255),

	ICON_URL VARCHAR(1000),
	ICON_FILE_TYPE VARCHAR(255),

	VIDEO_URL VARCHAR(1000),
	VIDEO_FILE_TYPE VARCHAR(255),

	unique index `ux_baas_service_ads_lang` (`SERVICE_CODE`, `LANGUAGE_ID`)
);

create table if not exists b_baas_package
(
	ID INT NOT NULL AUTO_INCREMENT,
	`CODE` VARCHAR(128) NOT NULL,

	ICON_CLASS VARCHAR(255),
	ICON_COLOR VARCHAR(255),
	ICON_STYLE VARCHAR(1000),

	PURCHASE_URL VARCHAR(1000),
	TITLE VARCHAR(255),
	DESCRIPTION VARCHAR(1000),
	FEATURE_PROMOTION_CODE VARCHAR(255),
	HELPER_CODE VARCHAR(255),
	DISTRIBUTION_STRATEGY VARCHAR(255),

	PRICE_VALUE DECIMAL(18,2) NOT NULL DEFAULT 0,
	PRICE_CURRENCY_ID VARCHAR(3),
	PRICE_DESCRIPTION VARCHAR(1000),

	ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
	SORT INT NOT NULL DEFAULT 100,

	LANGUAGE_INFO text,
	primary key (ID),
	unique index `ux_baas_packages` (`CODE`)
);

create table if not exists b_baas_service_in_package
(
	ID INT NOT NULL AUTO_INCREMENT,
	PACKAGE_CODE VARCHAR(128) NOT NULL,
	SERVICE_CODE VARCHAR(128) NOT NULL,
	`VALUE` INT NOT NULL DEFAULT 0,
	primary key (ID),
	unique index `ux_baas_s_i_p_services_code` (`SERVICE_CODE`, `PACKAGE_CODE`)
);

create table if not exists b_baas_purchase
(
	ID INT NOT NULL AUTO_INCREMENT,
	CODE VARCHAR(128) NOT NULL,
	PURCHASE_URL VARCHAR(1000),
	PURGED CHAR(1) NOT NULL DEFAULT 'N',
	NOTIFIED CHAR(1) NOT NULL DEFAULT 'N',

	unique index `ux_baas_purchase_code` (`CODE`),
	primary key (ID)
);

create table if not exists b_baas_purchased_package
(
	ID INT NOT NULL AUTO_INCREMENT,
	CODE VARCHAR(128) NOT NULL,
	PACKAGE_CODE VARCHAR(128) NOT NULL,
	PURCHASE_CODE VARCHAR(128) NOT NULL,

	START_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	EXPIRATION_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

	ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
	NOTIFIED CHAR(1) NOT NULL DEFAULT 'N',

	unique index `ux_baas_pp_code` (`CODE`),
	index `ux_baas_pp_code_pack_code` (`CODE`, `PACKAGE_CODE`),
	index `ux_baas_pp_code_purch_code` (`CODE`, `PURCHASE_CODE`),
	primary key (ID)
);

create table if not exists b_baas_service_in_purchased_pack
(
	ID INT NOT NULL AUTO_INCREMENT,
	PURCHASED_PACKAGE_CODE VARCHAR(128) NOT NULL,
	SERVICE_CODE VARCHAR(128) NOT NULL,
	CURRENT_VALUE INT NOT NULL DEFAULT 0,

	STATE_NUMBER INT DEFAULT NULL,

	primary key (ID),
	unique index `ux_baas_pps_pack_service` (`PURCHASED_PACKAGE_CODE`, `SERVICE_CODE`),
	index `ix_baas_psc_pack_service` (`SERVICE_CODE`, `CURRENT_VALUE`)
);
