<?php

return [
	'extensions' => [
		'analytics',
		'type',
		'im:messenger/const',
		'im:messenger/lib/di/service-locator',
		'im:messenger/lib/helper',
		'im:messenger/lib/logger',
		'im:messenger/lib/params',
		'im:messenger/lib/utils',
		'im:messenger/provider/data',
		'im:messenger/provider/services/analytics/helper',
	],
	'bundle' => [
		'./src/assistant-button',
		'./src/audio',
		'./src/chat-create',
		'./src/chat-delete',
		'./src/chat-open',
		'./src/chat-pin',
		'./src/collab-entities',
		'./src/dialog-edit',
		'./src/dialog-text-format',
		'./src/download-file',
		'./src/entity-manager',
		'./src/file-sending',
		'./src/helper',
		'./src/image-picker',
		'./src/message-create-menu',
		'./src/message-delete',
		'./src/message-pin',
		'./src/message-type',
		'./src/messenger',
		'./src/navigation-tab',
		'./src/notification',
		'./src/reaction',
		'./src/service',
		'./src/sticker',
		'./src/tariff-restrictions',
		'./src/video-note',
		'./src/mention',
		'./src/vote',
		'./src/search',
		'./src/recent',
	],
];
