<?php

return [
	'extensions' => [
		'alert',
		'analytics',
		'asset-manager',
		'bottom-sheet',
		'haptics',
		'layout/list-view-queue-worker',
		'layout/ui/loading-screen',
		'loc',
		'notify',
		'rest/run-action-executor',
		'toast',
		'tokens',
		'tourist',
		'ui-system/blocks/avatar',
		'ui-system/blocks/banners/card-banner',
		'ui-system/blocks/chips/chip-button',
		'ui-system/blocks/icon',
		'ui-system/form/buttons/button',
		'ui-system/layout/area',
		'ui-system/layout/area-list',
		'ui-system/layout/box',
		'ui-system/layout/card',
		'ui-system/layout/card-list',
		'ui-system/layout/dialog-footer',
		'ui-system/typography/heading',
		'ui-system/typography/text',
		'utils/enums/style',
		'utils/object',
	],
	'bundle' => [
		'./src/banners',
		'./src/preset-info',
		'./src/preset-manual/manual-bottom-list',
		'./src/preset-manual/manual-menu',
		'./src/utils',
	],
];
