CREATE TABLE IF NOT EXISTS b_booking_client_type(
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`MODULE_ID` VARCHAR(255) NOT NULL,
	`CODE` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX IX_BCT_MODULE_ID_CODE(`MODULE_ID`, `CODE`)
);

CREATE TABLE IF NOT EXISTS b_booking_resource_type(
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`MODULE_ID` VARCHAR(255) NOT NULL,
	`CODE` VARCHAR(255) DEFAULT NULL,
	`NAME` VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX IX_BRT_MODULE_ID_CODE(`MODULE_ID`, `CODE`)
);

CREATE TABLE IF NOT EXISTS b_booking_resource_type_notification_settings(
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`TYPE_ID` INT UNSIGNED NOT NULL,
	`IS_INFO_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_INFO` VARCHAR(255) NOT NULL,
	`INFO_DELAY` INT NOT NULL DEFAULT 0,
	`IS_CANCELLATION_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`CANCELLATION_DELAY` INT NOT NULL DEFAULT 600,
	`IS_CONFIRMATION_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_CONFIRMATION` VARCHAR(255) NOT NULL,
	`CONFIRMATION_DELAY` INT NOT NULL DEFAULT 86400,
	`CONFIRMATION_REPETITIONS` INT NOT NULL DEFAULT 0,
	`CONFIRMATION_REPETITIONS_INTERVAL` INT NOT NULL DEFAULT 10800,
	`CONFIRMATION_COUNTER_DELAY` INT NOT NULL DEFAULT 10800,
	`IS_REMINDER_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_REMINDER` VARCHAR(255) NOT NULL,
	`REMINDER_DELAY` INT NOT NULL DEFAULT -1,
	`IS_FEEDBACK_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_FEEDBACK` VARCHAR(255) NOT NULL,
	`IS_DELAYED_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_DELAYED` VARCHAR(255) NOT NULL,
	`DELAYED_DELAY` INT NOT NULL DEFAULT 300,
	`DELAYED_COUNTER_DELAY` INT NOT NULL DEFAULT 300,
	`SENDER_CODE` VARCHAR(255) NOT NULL DEFAULT 'bitrix24',
	PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_resource(
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`TYPE_ID` INT UNSIGNED NOT NULL,
	`EXTERNAL_ID` INT UNSIGNED DEFAULT NULL,
	`IS_MAIN` CHAR(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY (`ID`),
	INDEX IX_BR_TYPE_ID(`TYPE_ID`),
	INDEX IX_BR_EXTERNAL_ID(`EXTERNAL_ID`),
	INDEX IX_BR_IS_MAIN(`IS_MAIN`)
);

CREATE TABLE IF NOT EXISTS b_booking_resource_data(
	`ID`          INT UNSIGNED    NOT NULL AUTO_INCREMENT,
	`RESOURCE_ID` INT UNSIGNED NOT NULL,
	`AVATAR_ID` INT UNSIGNED DEFAULT NULL,
	`NAME`        VARCHAR(255)    NOT NULL,
	`DESCRIPTION` TEXT,
	`IS_DELETED` CHAR(1) NOT NULL DEFAULT 'N',
	`DELETED_AT`  TIMESTAMP NULL DEFAULT NULL,
	`CREATED_AT`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`CREATED_BY`  BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX IX_BRD_RESOURCE_ID(`RESOURCE_ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_resource_settings(
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`RESOURCE_ID` INT UNSIGNED NOT NULL,
	`WEEKDAYS` VARCHAR(50) NOT NULL,
	`SLOT_SIZE` INT UNSIGNED DEFAULT NULL,
	`TIME_FROM` INT UNSIGNED NOT NULL,
	`TIME_TO` INT UNSIGNED NOT NULL,
	`TIMEZONE` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_resource_notification_settings(
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`RESOURCE_ID` INT UNSIGNED NOT NULL,
	`IS_INFO_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_INFO` VARCHAR(255) NOT NULL,
	`INFO_DELAY` INT NOT NULL DEFAULT 0,
	`IS_CANCELLATION_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`CANCELLATION_DELAY` INT NOT NULL DEFAULT 600,
	`IS_CONFIRMATION_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_CONFIRMATION` VARCHAR(255) NOT NULL,
	`CONFIRMATION_DELAY` INT NOT NULL DEFAULT 86400,
	`CONFIRMATION_REPETITIONS` INT NOT NULL DEFAULT 0,
	`CONFIRMATION_REPETITIONS_INTERVAL` INT NOT NULL DEFAULT 10800,
	`CONFIRMATION_COUNTER_DELAY` INT NOT NULL DEFAULT 10800,
	`IS_REMINDER_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_REMINDER` VARCHAR(255) NOT NULL,
	`REMINDER_DELAY` INT NOT NULL DEFAULT -1,
	`IS_FEEDBACK_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_FEEDBACK` VARCHAR(255) NOT NULL,
	`IS_DELAYED_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_DELAYED` VARCHAR(255) NOT NULL,
	`DELAYED_DELAY` INT NOT NULL DEFAULT 300,
	`DELAYED_COUNTER_DELAY` INT NOT NULL DEFAULT 300,
	`SENDER_CODE` VARCHAR(255) NOT NULL DEFAULT 'bitrix24',
	PRIMARY KEY (`ID`),
	UNIQUE INDEX IX_BRNS_RESOURCE_ID(`RESOURCE_ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_booking(
	`ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(255) DEFAULT NULL,
	`DATE_FROM` BIGINT UNSIGNED NOT NULL,
	`DATE_TO` BIGINT UNSIGNED NOT NULL,
	`TIMEZONE_FROM` VARCHAR(50) NOT NULL,
	`TIMEZONE_FROM_OFFSET` INT NOT NULL,
	`TIMEZONE_TO` VARCHAR(50) NOT NULL,
	`TIMEZONE_TO_OFFSET` INT NOT NULL,
	`DATE_MAX` BIGINT UNSIGNED NOT NULL,
	`IS_RECURRING` CHAR(1) NOT NULL DEFAULT 'N',
	`RRULE` TEXT,
	`PARENT_ID` INT UNSIGNED DEFAULT NULL,
	`IS_DELETED` CHAR(1) NOT NULL DEFAULT 'N',
	`IS_CONFIRMED` CHAR(1) NOT NULL DEFAULT 'N',
	`DESCRIPTION` TEXT,
	`VISIT_STATUS` VARCHAR(20) NOT NULL DEFAULT 'unknown',
	`SOURCE` VARCHAR(20) NOT NULL DEFAULT 'internal',
	`DELETION_SCENARIO` VARCHAR(20) DEFAULT NULL,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`DELETED_AT` TIMESTAMP NULL DEFAULT NULL,
	`CREATED_BY` BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY (`ID`),
	INDEX IX_BB_IS_DELETED_DATE_FROM_DATE_MAX (`IS_DELETED`, `DATE_FROM`, `DATE_MAX`),
	INDEX IX_BB_IS_DELETED_DATE_MAX_DATE_FROM (`IS_DELETED`, `DATE_MAX`, `DATE_FROM`),
	INDEX IX_BB_DATE_FROM_DATE_TO(`DATE_FROM`, `DATE_TO`),
	INDEX IX_BB_DATE_MAX(`DATE_MAX`),
	INDEX IX_BB_PARENT_ID (`PARENT_ID`),
	INDEX IX_BB_CREATED_AT (`CREATED_AT`),
	INDEX IX_BB_CREATED_BY (`CREATED_BY`)
);

CREATE TABLE IF NOT EXISTS b_booking_booking_resource(
	`ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`BOOKING_ID` BIGINT UNSIGNED NOT NULL,
	`RESOURCE_ID` INT UNSIGNED NOT NULL,
	`IS_PRIMARY` CHAR(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (`ID`),
	UNIQUE INDEX IX_BBR_BOOKING_ID_RESOURCE(`BOOKING_ID`, `RESOURCE_ID`),
	INDEX IX_BBR_BOOKING_ID_IS_PRIMARY(`BOOKING_ID`, `IS_PRIMARY`)
);

CREATE TABLE IF NOT EXISTS b_booking_booking_client(
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`BOOKING_ID` BIGINT UNSIGNED DEFAULT NULL,
	`ENTITY_ID` BIGINT UNSIGNED NOT NULL,
	`CLIENT_TYPE_ID` INT UNSIGNED NOT NULL,
	`CLIENT_ID` INT UNSIGNED NOT NULL,
	`IS_PRIMARY` CHAR(1) NOT NULL DEFAULT 'N',
	`ENTITY_TYPE` VARCHAR(255) NOT NULL DEFAULT 'booking',
	PRIMARY KEY (`ID`),
	UNIQUE INDEX IX_BBC_ENTITY_ID_CLIENT(`ENTITY_ID`, `ENTITY_TYPE`, `CLIENT_TYPE_ID`, `CLIENT_ID`),
	INDEX IX_BBC_CLIENT(`CLIENT_TYPE_ID`, `CLIENT_ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_booking_external_data(
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`BOOKING_ID` BIGINT UNSIGNED DEFAULT NULL,
	`ENTITY_ID` BIGINT UNSIGNED NOT NULL,
	`MODULE_ID` VARCHAR(255) NOT NULL,
	`ENTITY_TYPE_ID` VARCHAR(255) NOT NULL,
	`VALUE`	VARCHAR(255) NOT NULL,
	`ENTITY_TYPE` VARCHAR(255) NOT NULL DEFAULT 'booking',
	PRIMARY KEY (`ID`),
	INDEX IX_BBED_ENTITY_ID_ENTITY_TYPE(`ENTITY_ID`, `ENTITY_TYPE`),
	INDEX IX_BBED_VALUE(`MODULE_ID`, `ENTITY_TYPE_ID`, `VALUE`)
);

CREATE TABLE IF NOT EXISTS b_booking_journal(
	`ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`ENTITY_ID` BIGINT UNSIGNED NOT NULL,
	`TYPE` VARCHAR(64) NOT NULL,
	`DATA` MEDIUMTEXT NOT NULL,
	`STATUS` VARCHAR(10) NOT NULL,
	`INFO` VARCHAR(512) DEFAULT NULL,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	INDEX IX_BJ_ENTITY (`ENTITY_ID`),
	INDEX IX_BJ_TYPE (`TYPE`),
	INDEX IX_BJ_STATUS (`STATUS`),
	INDEX IX_BJ_CREATED_AT (`CREATED_AT`)
);

CREATE TABLE IF NOT EXISTS b_booking_favorites(
	 `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	 `MANAGER_ID` BIGINT UNSIGNED NOT NULL,
	 `RESOURCE_ID` INT UNSIGNED NOT NULL,
	 `TYPE` VARCHAR(10) NOT NULL DEFAULT 'ADDED',
	 PRIMARY KEY (`ID`),
	 INDEX `IX_BF_RESOURCE` (`RESOURCE_ID`),
	 UNIQUE INDEX IX_BF_MANAGER_ID_RESOURCE(`MANAGER_ID`, `RESOURCE_ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_scorer (
	`ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`USER_ID` INT(11) NOT NULL DEFAULT 0,
	`ENTITY_ID` INT(11) NOT NULL DEFAULT 0,
	`TYPE` VARCHAR(64) NOT NULL DEFAULT '',
	`VALUE` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX IX_BS_USER_ID_ENTITY_ID_TYPE(`USER_ID`, `ENTITY_ID`, `TYPE`),
	INDEX `IX_BS_USER` (`USER_ID`),
	INDEX `IX_BS_TYPE` (`TYPE`),
	INDEX `IX_BS_ENTITY` (`ENTITY_ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_booking_note(
	`ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`BOOKING_ID` BIGINT UNSIGNED DEFAULT NULL,
	`ENTITY_ID` BIGINT UNSIGNED NOT NULL,
	`DESCRIPTION` TEXT NOT NULL,
	`ENTITY_TYPE` varchar(255) NOT NULL DEFAULT 'booking',
	`NOTE_TYPE` varchar(255) NOT NULL DEFAULT 'manager',
	PRIMARY KEY (`ID`),
	UNIQUE INDEX IX_BBN_ENTITY_ID_ENTITY_TYPE_NOTE_TYPE (`ENTITY_ID`, `ENTITY_TYPE`, `NOTE_TYPE`)
);

CREATE TABLE IF NOT EXISTS b_booking_option (
	ID int auto_increment not null,
	USER_ID int not null,
	NAME varchar(255) not null,
	VALUE varchar(255) not null,
	PRIMARY KEY (ID),
	UNIQUE INDEX ux_bk_option_user_id_name (USER_ID, NAME)
);

CREATE TABLE IF NOT EXISTS b_booking_booking_message(
	`ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`BOOKING_ID` BIGINT UNSIGNED NOT NULL,
	`NOTIFICATION_TYPE` VARCHAR(255) NOT NULL,
	`SENDER_MODULE_ID` VARCHAR(255) DEFAULT NULL,
	`SENDER_CODE` VARCHAR(255) NOT NULL,
	`EXTERNAL_MESSAGE_ID` VARCHAR(255) NOT NULL,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	INDEX IX_BBM_COMPLEX_1 (`BOOKING_ID`, `NOTIFICATION_TYPE`, `SENDER_CODE`, `CREATED_AT`),
	INDEX IX_BBM_MESSAGE(`SENDER_CODE`, `EXTERNAL_MESSAGE_ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_booking_message_failure_log(
	`ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`BOOKING_ID` BIGINT UNSIGNED NOT NULL,
	`NOTIFICATION_TYPE` VARCHAR(255) NOT NULL,
	`SENDER_MODULE_ID` VARCHAR(255) NOT NULL,
	`SENDER_CODE` VARCHAR(255) NOT NULL,
	`REASON_CODE` VARCHAR(255) NOT NULL,
	`REASON_TEXT` TEXT,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	INDEX IX_BBMFL_COMPLEX_1 (`BOOKING_ID`, `NOTIFICATION_TYPE`, `SENDER_MODULE_ID`, `SENDER_CODE`, `CREATED_AT`),
	INDEX IX_BBMFL_COMPLEX_2 (`BOOKING_ID`, `NOTIFICATION_TYPE`, `CREATED_AT`)
);

CREATE TABLE IF NOT EXISTS b_booking_wait_list_item (
	`ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`CREATED_BY` int8 NOT NULL,
	`CREATED_AT` timestamp DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp DEFAULT CURRENT_TIMESTAMP,
	`IS_DELETED` CHAR(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (`ID`),
	INDEX IX_BWLI_IS_DELETED(`IS_DELETED`)
);

CREATE TABLE IF NOT EXISTS b_booking_resource_linked_entity (
	`ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`RESOURCE_ID` BIGINT UNSIGNED NOT NULL,
	`ENTITY_ID` BIGINT UNSIGNED NOT NULL,
	`ENTITY_TYPE` varchar(255) NOT NULL,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`DATA` TEXT DEFAULT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX IX_BRE_RESOURCE_ENTITY(`RESOURCE_ID`, `ENTITY_ID`, `ENTITY_TYPE`)
);

CREATE TABLE IF NOT EXISTS b_booking_delayed_task (
	`ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`CODE` varchar(32) NOT NULL,
	`TYPE` varchar(64) NOT NULL,
	`DATA` TEXT NOT NULL,
	`STATUS` varchar(10) NOT NULL,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	INDEX IX_BDT_STATUS (`STATUS`)
);

CREATE TABLE IF NOT EXISTS b_booking_booking_sku (
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`BOOKING_ID` INT UNSIGNED NOT NULL,
	`SKU_ID` INT UNSIGNED NOT NULL,
	`PRODUCT_ROW_ID` INT UNSIGNED DEFAULT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX UX_BBS_BOOKING_SKU(`BOOKING_ID`, `SKU_ID`),
	UNIQUE INDEX UX_BBS_PRODUCT_ROW(`PRODUCT_ROW_ID`),
	INDEX IX_BBS_SKU_ID(`SKU_ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_resource_sku (
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`RESOURCE_ID` INT UNSIGNED NOT NULL,
	`SKU_ID` INT UNSIGNED NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX UX_BRS_RESOURCE_SKU(`RESOURCE_ID`, `SKU_ID`),
	INDEX IX_BRS_SKU_ID(`SKU_ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_resource_sku_yandex (
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`RESOURCE_ID` INT UNSIGNED NOT NULL,
	`SKU_ID` INT UNSIGNED NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX UX_BRSY_RESOURCE_SKU(`RESOURCE_ID`, `SKU_ID`),
	INDEX IX_BRSY_SKU_ID(`SKU_ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_booking_payment (
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`BOOKING_ID` INT UNSIGNED NOT NULL,
	`PAYMENT_ID` INT UNSIGNED NOT NULL,
	`IS_PAID` CHAR(1) NOT NULL DEFAULT 'N',
	`IS_PAID_MANUALLY` CHAR(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (ID),
	UNIQUE INDEX IX_BBP_PAYMENT_ID(`PAYMENT_ID`)
);
